language: go

go:
  - 1.3
  - 1.4
  - tip

install:
  - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-1_amd64.deb"
  - sudo dpkg -i shellcheck_0.3.7-1_amd64.deb
  - go get github.com/stretchr/testify/mock
  - go get github.com/tools/godep
  - go get -u github.com/cep21/goverify
  - gem install mdl
  - go get -d -v ./... && go build -v ./...

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ./travis_check.sh
